services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: sns-archive-jwt-db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    stdin_open: true
    tty: true
volumes:
  db-data:
    driver: local
